### ISSUE TITLE
Bitcode issue

### ISSUE THREAD

**Issue by tGilani** [linkedin/LayoutTest-iOS#12]
I am trying to integrate LayoutTest library 1.2.1 into a project that does not yet suppot BitCode, through cocoa pods that generats dynamic frameworks. However, Xcode gives me following error 

`does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64.
`
After disabling the bitcode in Pod project, it beings to work. I wonder why other libraries who have BitCode enabled work fine but LayoutTest doesn't.

I ended up disabling BitCode for all Pods using the link below.
http://stackoverflow.com/questions/32640149/disable-bitcode-for-project-and-cocoapods-dependencies-with-xcode7

**Comment by plivesey** [comment]
Turns out for some reason I wasn't watching the repo so didn't get this notification. Sorry about that.

Are you using Swift or just the Objective-C version? I don't know much about bitcode and how it's meant to be set up. Perhaps a sample app may help? It may be because it includes XCTest which may not support bitcode?

You're only adding it to your test target right?

**Comment by plivesey** [comment]
Honestly, I'm guessing this is really a cocoapods issue. It seems like you need to disable bitcode in all pods if your app doesn't support bitcode. It's unclear why this was only a problem for this library though.

Going to close this for now since you have a solution. Feel free to open it again if you want to keep discussing.

**Comment by tGilani** [comment]
Yes I had to disable bitcode through cocoapods but not on my project but on all pods.
