### ISSUE TITLE
LayoutTest 4.0.2 crashes with autolayout failures

### ISSUE THREAD

**Issue by brennantaylor** [linkedin/LayoutTest-iOS#48]
💥

Induce an autolayout failure for a simple test case and we see that the test suite terminates instead of failing the individual test. At least we know what test is having an issue.

**Comment by plivesey** [comment]
Sorry to be slow to respond to this. This certainly isn't preferable. I'm going to be out of the country and off internet for 3 weeks, so won't have time to take a look at this.

A PR would be welcome. Otherwise, I'll take a look sometime in a month or so.

As you say, seems noncritical since it is a failure, but would definitely like to fix this.

**Comment by brennantaylor** [comment]
Seems like this was an issue with our auto layout swizzler conflicting. We've resolved the issue. Not a problem with the lib. Thanks for the reply.

**Comment by plivesey** [comment]
Ah, amazing. Thanks for following up on this :D
